
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author srlab10
 */
public class Housekeeping extends javax.swing.JFrame {

    /**
     * Creates new form Housekeeping
     */
    public Housekeeping() {
        initComponents();
    }
public static Connection getConnection() throws ClassNotFoundException {

    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","demo");
        return con;
    }

    catch(Exception e){
        System.out.println(e.getMessage());
        return null;
    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 400));
        setPreferredSize(new java.awt.Dimension(900, 720));
        getContentPane().setLayout(null);

        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 200, 110, 29);

        jButton2.setText("Mark Cleaned");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(480, 200, 140, 29);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Number", "Room Type", "Arrival Date", "Departure Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 240, 471, 212);

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Housekeeping");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 110, 290, 70);

        jLabel3.setFont(new java.awt.Font("Papyrus", 0, 36)); // NOI18N
        jLabel3.setText("The Tropical ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 10, 230, 70);

        jLabel4.setText("An AP Group Hotel");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 60, 130, 16);

        jButton3.setText("Go Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(510, 460, 120, 29);

        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(170, 200, 97, 29);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 1450, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        DefaultTableModel model=(DefaultTableModel)
        jTable1.getModel();
        try{
            Connection con= getConnection();
            Statement stmt=(Statement) con.createStatement();
            String query="Select RoomNo, Roomtype, ArrivalDate, DepartureDate From roombooking where cleaned = 'no';";
     
            ResultSet rs=stmt.executeQuery(query);
            int i=0;
            while(rs.next()){
                String RoomNo=rs.getString("RoomNo");    
                String Roomtype=rs.getString("Roomtype");
                String ArrivalDate=rs.getString("ArrivalDate");
                String DepartureDate=rs.getString("DepartureDate");
                model.addRow(new Object[] {RoomNo,Roomtype,ArrivalDate, DepartureDate});
                i=i+1;
            }
            if (i==0){
                JOptionPane.showMessageDialog(this, "No room left for cleaning");
            }
        }
        
        catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int i = jTable1.getSelectedRow();
        Object a = jTable1.getValueAt(i,0);
        String b= a.toString();
        try{
            Connection con1= getConnection();
            Statement stmt1 =(Statement) con1.createStatement();
            String query1= "Update roombooking set cleaned='yes' where roomno='"+b+"';";
            stmt1.executeUpdate(query1);
            JOptionPane.showMessageDialog(this, "room has been marked as cleaned");
        }
         catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Home e = new Home();
        e.setVisible(true);
        this.setVisible(false);   
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        try{
            Connection con= getConnection();
            Statement stmt=(Statement) con.createStatement();
            String query="Select RoomNo From roombooking where booked='yes' and DepartureDate < CURDATE();";
            ResultSet rs=stmt.executeQuery(query);
            int i=0;
            
            while(rs.next()){
                String RoomNo=rs.getString("RoomNo");    
                i=i+1;
                Statement stmt1 =(Statement) con.createStatement();
                String query1= "Update roombooking set cleaned='no' where roomno='"+RoomNo+"';";
                stmt1.executeUpdate(query1);
            }
            
        }
        
        catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Housekeeping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Housekeeping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Housekeeping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Housekeeping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Housekeeping().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
